### PR TITLE
Update Conference Cards & Update CV Model

### PR DESCRIPTION
**Pull request by kilianpichard**
Update Conference Cards & Update CV Model

### CODE REVIEW

**Review by iti98 — DISMISSED** [review]
lgtm

**Comment by iti98** [comment]
Juste un problème d'alignement sur les conférences

Screenshot_2023-05-25-12-35-35-16_f73b71075b1de7323614b647fe394240

**Review by iti98 — COMMENTED** [review]
Unfortunately don't solve the visual issue

**Review by remirubis — APPROVED** [review]
Bien plus beau, thanks !

**Pull request merged**
